"""Writes report/kan_rec_report.tex: the whole report as one self-contained LaTeX file.

Inlines every \\input (preamble, chapters, appendix, references), the notebook-generated tables
and macros, and the code listings. Figures stay as \\genfigure / \\includegraphics references with a
placeholder fallback, so the file compiles on its own (e.g. pasted into Overleaf) and shows the
figures when the PDFs from report/figures/ are uploaded next to it.

    uv run python tools/flatten_report.py
"""
import re
import zipfile
from pathlib import Path

REPORT = Path(__file__).resolve().parent.parent / "report"
OUT = REPORT / "kan_rec_report.tex"
ZIP = REPORT / "kan_rec_report_overleaf.zip"


def tex_path(name):
    p = REPORT / name
    return p if p.suffix == ".tex" else p.with_suffix(".tex")


def generated_table(m):
    p = REPORT / "generated" / m.group(1)
    if p.exists():
        return f"% generated/{m.group(1)}\n" + p.read_text().strip() + "\n"
    return (r"\begin{center}\fbox{\parbox{0.8\textwidth}{\centering\small Table \texttt{generated/"
            + m.group(1).replace("_", r"\_") + r"} is produced by \texttt{kan\_rec.ipynb}.}}\end{center}")


def listing(m):
    opts, path = m.group(1), m.group(2)
    lines = (REPORT / path).resolve().read_text().splitlines()
    rng = re.search(r"linerange=\{(\d+)-(\d+)\}", opts)
    if rng:
        lines = lines[int(rng.group(1)) - 1:int(rng.group(2))]
    opts = re.sub(r",?\s*linerange=\{\d+-\d+\}", "", opts)
    return "\\begin{lstlisting}[" + opts + "]\n" + "\n".join(lines) + "\n\\end{lstlisting}"


def expand(text, depth=0):
    if depth > 5:
        raise RecursionError("too many nested \\input")

    def inline(m):
        name = m.group(1)
        if name.startswith("generated/"):
            p = REPORT / name
            return p.read_text().strip() if p.exists() else ""
        return f"% ---- {name} ----\n" + expand(tex_path(name).read_text(), depth + 1)

    text = re.sub(r"\\IfFileExists\{generated/kan_linearity\.tex\}\{\\input\{generated/kan_linearity\.tex\}\}\{(.*)\}",
                  lambda m: (REPORT / "generated" / "kan_linearity.tex").read_text().strip()
                  if (REPORT / "generated" / "kan_linearity.tex").exists() else m.group(1), text)
    text = re.sub(r"\\generated\{([^}]+)\}", generated_table, text)
    text = re.sub(r"\\lstinputlisting\[(.*?)\]\{([^}]+)\}", listing, text, flags=re.S)
    return re.sub(r"(?<!\\newcommand\{)\\input\{([^}]+)\}", inline, text)


def main():
    text = expand((REPORT / "main.tex").read_text())
    header = ("% Kolmogorov-Arnold Networks in Recurrent Recommenders: complete report in one file.\n"
              "% Generated by tools/flatten_report.py from report/main.tex; edit the sources, not this file.\n"
              "% Compile with xelatex/tectonic or pdflatex (Overleaf). Optional files next to it:\n"
              "%   figures (*.pdf from report/figures/) and upes_logo.png; missing ones show as placeholders.\n")
    text = "\n".join(line.encode("ascii", "ignore").decode() if line.lstrip().startswith("%") else line
                     for line in text.splitlines())
    non_ascii = [i + 1 for i, line in enumerate(text.splitlines()) if not line.isascii()]
    if non_ascii:
        raise ValueError(f"non-ASCII characters outside comments on lines {non_ascii[:10]}")
    OUT.write_text(header + text + "\n")
    leftover = re.findall(r"\\(?:input|lstinputlisting)\{", text)
    with zipfile.ZipFile(ZIP, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(OUT, OUT.name)
        for f in sorted((REPORT / "figures").glob("*.pdf")) + sorted((REPORT / "assets").glob("*")):
            z.write(f, f.name)
    print(f"wrote {OUT} ({len(text.splitlines())} lines); unresolved inputs: {len(leftover)}")
    print(f"wrote {ZIP} ({len(zipfile.ZipFile(ZIP).namelist())} files) for Overleaf: New Project > Upload Project")


if __name__ == "__main__":
    main()
